// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsd6RH9AhfBR2IQ4Ggn00K5PQb-ZPCkTk',
    appId: '1:597728781701:web:54879df9241dff14c6d0ec',
    messagingSenderId: '597728781701',
    projectId: 'todo-spring-2025-0',
    authDomain: 'todo-spring-2025-0.firebaseapp.com',
    storageBucket: 'todo-spring-2025-0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0DwL5MWQ85msIlEvTzQLL1lehZoEs1o',
    appId: '1:597728781701:android:cbd5b8da0c65ca25c6d0ec',
    messagingSenderId: '597728781701',
    projectId: 'todo-spring-2025-0',
    storageBucket: 'todo-spring-2025-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPcraoJTOwmVn_JYSJ1Tr_MbPhO1Eihag',
    appId: '1:597728781701:ios:cbfb5399218726ecc6d0ec',
    messagingSenderId: '597728781701',
    projectId: 'todo-spring-2025-0',
    storageBucket: 'todo-spring-2025-0.firebasestorage.app',
    iosBundleId: 'com.example.todoSpring2025',
  );
}
